import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import localFont from "next/font/local";
import "./globals.css";
import DateFilter from "@/components/date-filter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <div className="flex flex-col gap-4 p-2">
            <Header />
            {children}
          </div>
        </NuqsAdapter>
      </body>
    </html>
  );
}

function Header() {
  return <DateFilter id="datetime" label="DateTime Range" />;
}
